# Generated by Django 5.1.2 on 2024-11-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
